theme: jekyll-theme-cayman
title: "COVID19 🇸🇪🇩🇰🇳🇴🇫🇮🇮🇸 Analysis"
description: "Trend Tracking the Nordic Countries"
github:
  show_downloads: false
  is_project_page: false
  html_show_sourcelink: false
